# Generated by Django 5.2.1 on 2025-06-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, help_text='Enfermedades hereditarias o comunes en la familia.', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='antecedentes_nutricionales',
            field=models.TextField(blank=True, help_text='Patrón alimentario, hábitos, actividad física, restricciones, síntomas digestivos.', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='antecedentes_personales',
            field=models.TextField(blank=True, help_text='Enfermedades crónicas, alergias, cirugías, tratamientos, embarazo/lactancia, etc.', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='estado_nutricional_global',
            field=models.TextField(blank=True, help_text='ESG, escalas de riesgo, síntomas, apoyo social, motivación, factores psicológicos.', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='evaluacion_antropometrica',
            field=models.TextField(blank=True, help_text='Peso, talla, IMC, perímetros, pliegues, composición corporal, evolución.', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='evaluacion_bioquimica',
            field=models.TextField(blank=True, help_text='Glucemia, perfil lipídico, hemograma, función hepática, otros análisis.', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='plan_alimentacion',
            field=models.TextField(blank=True, help_text='Objetivos, calorías, macronutrientes, plan de comidas, recomendaciones, guías, estrategias.', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='seguimiento',
            field=models.TextField(blank=True, help_text='Notas de progreso, cambios, resultados, cumplimiento, ajustes, próxima cita.', null=True),
        ),
    ]
